services:
  it-tools:
    image: corentinth/it-tools:latest
    container_name: it-tools
    restart: unless-stopped
    ports:
      - 8085:80
    networks:
      - homelab_network

networks:
  homelab_network:
    external: true
