services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8000:80/tcp"
      - "8443:443/tcp"
      - "67:67/udp"
    env_file:
      - .env
    environment:
      WEBPASSWORD: ${ADMIN_PASSWORD}
      TZ: "Europe/London"
      FTLCONF_dns_listeningMode: "all"
    volumes:
      - config:/etc/pihole
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      - NET_ADMIN
    restart: unless-stopped
    networks:
      - homelab_network

networks:
  homelab_network:
    external: true

volumes:
  config:
    driver: local
