services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ~/homelab_volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/homelab_volumes/nginx/sites-enabled:/etc/nginx/sites-enabled
    networks:
      - homelab_network
    ports:
      - "80:80"
      - "443:443"

networks:
  homelab_network:
    external: true
