services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9000:9000
      - 9443:9443
    volumes:
      - ~/homelab_volumes/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - homelab_network
    restart: unless-stopped

networks:
  homelab_network:
    external: true
