networks:
  homelab_network:
    external: true
  default:
    name: media-stack

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    ports:
      - "8096:8096"
    environment:
      TZ: ${TZ}
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ./config/jellyfin:/config
      - ./cache/jellyfin:/cache
      - /media:/media
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    ports:
      - "8088:8088"
      - "6881:6881"
      - "6881:6881/udp"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      WEBUI_PORT: 8088
    volumes:
      - ./config/qbittorrent:/config
      - /media/downloads:/downloads
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    ports:
      - "9696:9696"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ./config/prowlarr:/config
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    ports:
      - "8989:8989"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ./config/sonarr:/config
      - /media:/media
      - /media/downloads:/downloads
    restart: unless-stopped
    depends_on:
      - qbittorrent
      - prowlarr

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    ports:
      - "7878:7878"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ./config/radarr:/config
      - /media:/media
      - /media/downloads:/downloads
    restart: unless-stopped
    depends_on:
      - qbittorrent
      - prowlarr

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    ports:
      - "6767:6767"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ./config/bazarr:/config
      - /media:/media
    restart: unless-stopped
    depends_on:
      - sonarr
      - radarr
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    ports:
      - "8191:8191"
    environment:
      - LOG_LEVEL=info
      - TZ=${TZ}
    restart: unless-stopped
