services:
  glance:
    container_name: glance
    image: glanceapp/glance:latest
    restart: unless-stopped
    volumes:
      - ~/homelab_volumes/glance_config:/app/config
    ports:
      - 8080:8080
